### ISSUE TITLE
translate and issues (spoilers)

### ISSUE THREAD

**Issue by nice2cu1** [AnonymousStrangerOW/TheStrangerTheyAre#6]
1. I have already filled the text into the corresponding key-value pairs, but it seems that it has not been correctly recognized. I can confirm that there are no structural issues with this JSON file and the error only exists in the prompt text for interactive actions that need to be displayed in the HUD.
2. A question about the invisibility of artifacts in the simulation station. I can't describe this issue in English, but I will upload a video (the video will more clearly demonstrate the issue).

![Image](https://github.com/user-attachments/assets/0cf4c0a3-b4e2-4820-9a1c-6d1094802cc9)

![Image](https://github.com/user-attachments/assets/09064fc6-8846-4fd5-b5c0-bd97682c2948)

![Image](https://github.com/user-attachments/assets/4b04e7b0-486b-4464-97dd-7d21f53def8e)

https://github.com/user-attachments/assets/80954225-b0ab-491c-8ec7-3183aef9a179

**Comment by nice2cu1** [comment]
UPDATE: Placing these name translations into the DialogueDictionary structure allows the translation to work properly, but the five Seals still cannot be translated.

![Image](https://github.com/user-attachments/assets/eff1363d-66f6-449c-b542-8a5b0fa03381)

**Comment by nice2cu1** [comment]
https://github.com/user-attachments/assets/80954225-b0ab-491c-8ec7-3183aef9a179

**Comment by AnonymousStrangerOW** [comment]
1. oh yeah the seals themselves have their names hardcoded and aren't really translation friendly (my bad). for now you could probably write a script that changes it during runtime. the code for seals is in Seals.cs
2. this artifact bug has been reported several times and i have never been able to reproduce it. to remedy the effect, go to the artifact pedestal and place it down and pick it up again.
3. please keep in mind my english.json is out of date, so you may have to update some text for certain dialogue and shiplogs, especially in areas where players have struggled a lot.

**Comment by nice2cu1** [comment]
1. This is bad news: Currently, my PC does not have a development environment, and in the short term, the hardcoding issue cannot be resolved on my end.
2. Hope there's a better fix. This issue will puzzle first-time visitors. Once this error occurs, the very first artifact that is picked up will be unable to perform actions like focusing, leaving those visitors trapped in this simulation.
3. I'm translating on the fly while playing, so I can really feel the issue. I've added the missing text to the end of the corresponding sections (tI might have missed a few), but I can't update the english.json file at the same time. Sorry about that—— I just don't have any more time to spare for this.
4. This story is awesome—I really love it, except for the jumping steps in the simulation and the angler fish.🥲

**Comment by AnonymousStrangerOW** [comment]
why did you close the issue? i did the hardcoding thing and updated the english.json so everything should be fixed now for translations. i'll handle the updating the english.json from here on out. the artifact i now know what's causing it, but i haven't found a solution yet. i'll keep this issue open until i fix the artifact issue.

**Comment by nice2cu1** [comment]
oh, sorry! I didn't check your TODO, so I closed the issue. Also, I was wondering—why are there two english.json files in the f8e70a0 update? The one in translations has a breaking change, which is frustrating for translators (there's quite a lot of text to go through). Even though I know the content is still the same as before, it makes translation work harder since we can't easily tell if any new dialogues were added in this update.

**Comment by AnonymousStrangerOW** [comment]
the other english.json is a backup i thought i put outside of the repo (i didn't lol). the one in translations is the one you want to edit. at the moment, i can't think of a way to constantly inform you of dialogue changes, since there's so much that still needs to be done and updates to the text happen almost every day. i'll try to compile a diff list to show which lines can change. i can work with you however to test it in-game and see which lines need changed, which i did with another translator. you can find me on the outer wilds modding server for easier and quicker contact.

**Comment by AnonymousStrangerOW** [comment]
ok so i just pushed to the github your simplified chinese .json, and within it i made some small changes to get it up to date. there are a few small things you should have left to worry about translating.

i'm not sure if this is correct or not since i am not familiar with chinese. this dialogue was changed to one sentence due to a typo and redundancy. if it's not correct, feel free to correct it.
line 1131: "The Distant Enigma is the fourth planet of the Strangers' Homeworld.": "深域幻星是外星站居民星系的第四颗行星。",

new things that need translated:
line 1499: "AnonymousStrangerOW.StrangerSystem": "Stranger System", (this is the name of the star system, only worry about the "Stranger System" part)
line 1540: "Skull": "Skull",
line 1541: "Mineral": "Mineral",
line 1545: "Nearest Neighbor": "Nearest Neighbor",

and that should be it.

**Comment by AnonymousStrangerOW** [comment]
chinese simplified is in v2.2.0 and other issues are brought up in the other open issue already.
